name: distill_ds
description: Distill Design System - A modern, state-aware component library for Flutter.
version: 0.1.0
publish_to: none

environment:
  sdk: ">=3.7.0 <4.0.0"
  flutter: ">=3.29.0"

dependencies:
  flutter:
    sdk: flutter
  lucide_icons_flutter: ^3.1.9
  flutter_svg: ^2.0.16
  hugeicons:
    hosted: https://onepub.dev/api/kdpxxpsdav/
    version: ^1.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/svgs/
    - assets/logos/

  fonts:
    - family: GeistVariable
      fonts:
        - asset: assets/fonts/GeistVariable.ttf
        - asset: assets/fonts/GeistVariable-Italic.ttf
          style: italic
    - family: GeistMonoVariable
      fonts:
        - asset: assets/fonts/GeistMonoVariable.ttf

