name: distill_ds
description: Distill Design System - A modern, state-aware component library for Flutter.
version: 0.1.0
publish_to: none

environment:
  sdk: ">=3.7.0 <4.0.0"
  flutter: ">=3.29.0"

dependencies:
  flutter:
    sdk: flutter
  lucide_icons_flutter: ^3.1.9
  flutter_svg: ^2.0.16

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/svgs/

  fonts:
    - family: InterVariable
      fonts:
        - asset: assets/fonts/InterVariable.ttf
        - asset: assets/fonts/InterVariable-Italic.ttf
          style: italic
    - family: JetBrainsMono
      fonts:
        - asset: assets/fonts/JetBrainsMono-Regular.ttf
        - asset: assets/fonts/JetBrainsMono-Medium.ttf
          weight: 500
        - asset: assets/fonts/JetBrainsMono-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/JetBrainsMono-Bold.ttf
          weight: 700

